# 20SW062 Lab#3

# Task#01

In [3]:
import numpy as np

In [5]:
X = np.arange(2, 33, 2).reshape((4, 4))
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


# Task#02

In [8]:
arr = np.arange(1, 26).reshape(5,5)

even = arr[arr%2 == 0]
print(even)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [10]:
X = np.arange(1, 26).reshape(5,5)

y = arr[X%2 == 1]
print(y)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


# Task#03

In [13]:
X = np.array([1, 2, 3, 4]) + np.zeros((4,4))
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
